config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # CRUD

  #CREATE
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  #READ
  # read all
  get 'tasks', to: 'tasks#index'
  # read one
  get 'tasks/:id', to: 'tasks#show', as: 'task'

  #UPDATE
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  patch 'tasks/:id', to: 'tasks#update'

  #DELETE
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    # raise
    #find task by id and assign it to a variable
    # @task = Task.find(params[:id])
    # raise
    @task_status = completed?
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task)
  end

  def edit
    #find task by id and assign it to a variable
  end

  def update
    #find task by id and assign it to a variable

    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    #find task by id and assign it to a variable
    @task.destroy

    redirect_to tasks_path
  end

  def completed?
    if @task.completed
      'This task is complete'
    else
      'This task is incomplete'
    end
  end


  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for(task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <% if @task.persisted? %>
    <%= f.input :completed %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/tasks/destroy.html.erb
<div class="container col-8">
  <%= render "form", task: @task %>
</div>

app/views/tasks/edit.html.erb
<div class="container col-8">
  <h1>Edit task</h1>
  <%= render "form", task: @task %>
</div>

app/views/tasks/index.html.erb
<div class="container col-8">
  <h1>My tasks</h1>

  <form action="">
    <% @tasks.each do |task| %>
      <% if task.completed %>
        <input type="checkbox" id="task<%= task.id %>" name="task<%= task.id %>" value="task" checked>
      <% else %>
        <input type="checkbox" id="task<%= task.id %>" name="task<%= task.id %>" value="task">
      <% end %>
      <label for="task<%= task.id %>"><%= link_to task.title, task_path(task) %> <%= link_to "X", task_path(task), method: :delete, data: { confirm: "Are you sure?" } %></label>
      <br>
    <% end %>
  </form>
  <br>
  <%= link_to '+ Add a task', tasks_new_path %>
</div>

app/views/tasks/new.html.erb
<div class="container col-8">
  <h1>Add task</h1>
  <%= render "form", task: @task %>
</div>

app/views/tasks/show.html.erb
<div class="container col-8">
  <h1><%= @task.title %></h1>

  <%= link_to 'Edit task', edit_path %>

  <p><%= @task.details %></p>


  <form action="">
    <% if @task.completed%>
      <input type="checkbox" id="task<%= @task.id %>" name="task<%= @task.id %>" value="task" checked>
    <% else %>
      <input type="checkbox" id="task<%= @task.id %>" name="task<%= @task.id %>" value="task">
    <% end %>
    <label for="task<%= @task.id %>"><%= @task_status %></label>
    <br>
  </form>

  <br>

  <%= link_to 'Back to list', tasks_path %>

</div>